### PR TITLE
Add i18n support(bug have critical bug,only suggestion.)

### PR DESCRIPTION
**Pull request by edouardlicn**
I used https://www.npmjs.com/package/i18n-nodejs lib to control the translation,but as my skill it seems to fail to run it.You may check this if you can fix it.With i18n lib the translation mechanic will be a great upgrade.

### CODE REVIEW

**Comment by MarkCavalli** [comment]
What about single translation file. Here is some disadvantages:
1) Bad future support. If you want to del some strings, you need 100% confidence that string dont use something else.

But i will take a look at it

**Comment by edouardlicn** [comment]
I just give u a suggestion,and i dont use it by now.

**Comment by MarkCavalli** [comment]
Found a good way to store i18n in one file
Now its looks like this:
`const i18n = {
	basic: {

	},

	sMoney: {
		enterATM: {
			eng: 'Press ~b~E ~s~to open ATM Menu',
			rus: 'Нажмите ~b~E ~s~для входа в меню банкомата',
			ger: '',
			br: 'Pressione ~b~E ~s~para abrir o menu do Caixa Eletrônico', 
			zhs: '按 ~b~E ~s~ 键打开ATM菜单',
			zht: '按 ~b~E ~s~ 鍵打開ATM菜單',
		},

		notEnoughCash: {
			eng: 'Not enough cash!',
			rus: 'Недостаточно наличных!',
			ger: 'Nicht genug Geld!',
			br: 'O dinheiro não é suficiente!', 
			zhs: '现金不足!',
			zht: '現金不足!',
		},

		addBankMoney: {
			eng: 'New payment:',
			rus: 'Новый чек:',
			ger: 'Neue zahlung:',
			br: 'Novo pagamento:', 
			zhs: '新的支付:',
			zht: '新的支付:',
		},

		payTaxOffline: {
			eng: 'New tax payment:',
			rus: 'Новый налоговый чек:',
			ger: 'Neue tax zahlung:',
			br: 'Novo pagamento de imposto:', 
			zhs: '新的税务支出:',
			zht: '新的稅務支出:',
		},

		newFine: {
			eng: 'New fine:',
			rus: 'Новый штраф:',
			ger: '',
			br: 'Nova multa:', 
			zhs: '新的惩罚:',
			zht: '新的懲罰:',
		},
	},
}`

**Comment by edouardlicn** [comment]
You make the structure and I take the translation.

**Pull request closed without merging**
