### PR TITLE
Create installtionguild_linux

### PR DESCRIPTION
**Pull request by maramail**

### CODE REVIEW

**Comment by MarkCavalli** [comment]
Hi maramail! I dont want to create a lot of other files, so i put your guide into Readme.md.
Thank you for your help! =)

**Comment by maramail** [comment]
thx for reply.and some more question.
1:are u going to make i18n?
2:why not post file on rage's file section?

**Comment by maramail** [comment]
and 3:can other make plugin for it just like ex-extend on five-m?

**Comment by MarkCavalli** [comment]
1) Didn't think about that, but it looks good! 
2) I dont like a lot of 'trash' ( sorry =) ) in repository, so all user information should be in one file. Here is on git it Readme.md.
3) What do you mean 'plugin'?

**Comment by maramail** [comment]
2 no i means post on forum‘s file section.

**Pull request closed without merging**
