### PR TITLE
Added czech lang

### PR DESCRIPTION
**Pull request by rex2630**
And again, i hope its alright. Otherwise tell me, i will fix it

### CODE REVIEW

**Comment by MarkCavalli** [comment]
Did you tested it? =)

**Comment by rex2630** [comment]
No, i didnt. I just added strings how i seen them. What can could really go wrong about that?

**Comment by MarkCavalli** [comment]
Its okay, but it will not work. You translated only one file in clientside. We have serverside translations too.
Also check cMisc 32 string. There are bindings for languages in clientside

**Comment by rex2630** [comment]
Updated. Sorry for so many pull requests, but i dont know how to make it in one. I hope its alright now

**Comment by MarkCavalli** [comment]
You can update your branch with pr opened here.
Also check sMenu 25
And then i think it will works fine

**Comment by rex2630** [comment]
ERROR in ./app/server/sI18n.js 111:6
Module parse failed: Unexpected token (111:6)
You may need an appropriate loader to handle this file type.
|                       zhs: '▒',
|                       zht: '▒',
>                       cs 'sekund',
|               },
|
 @ ./app/server/Basic/sChat.js 2:13-32
 @ ./app/server/index.js

**Comment by rex2630** [comment]
oh, i see where is the problem. My bad

**Comment by rex2630** [comment]
Ok, now its working.  Tested :)

**Comment by rex2630** [comment]
But there is a small problem. Menu isnt showing anything..

**Comment by rex2630** [comment]
Ok, i managed to fix that. I will pull another request, if i will find another error

**Comment by MarkCavalli** [comment]
Good job, thank you =)

**Comment by rex2630** [comment]
np. I thank yout for this really great job. I just  with that there was more updates :/ like food reequirement,pee and poop, mobile phone and etc..

**Pull request merged**
